{
 "title": "LLM Usage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Gen.AI Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, max(Value) FROM $table WHERE $timeFilter \nAND MetricName = 'gen_ai.total.requests'\nGROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, max(Value) FROM base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1753287246,3) AND TimeUnix <= toDateTime64(1753290846,3) \nAND MetricName = 'gen_ai.total.requests'\nGROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Total Gen.AI Usage Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    $timeSeries AS time,\n    sum(Sum) AS total_sum,\n    ServiceName,\n    MetricName\nFROM $table\nWHERE \n    $timeFilter\n    AND MetricName = 'gen_ai.usage.cost'\n    AND ServiceName = 'chatterbox-api'\nGROUP BY time, ServiceName, MetricName\nORDER BY time",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT \n    (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS time,\n    sum(Sum) AS total_sum,\n    ServiceName,\n    MetricName\nFROM base14.otel_metrics_histogram\nWHERE \n    TimeUnix >= toDateTime64(1753325311,3) AND TimeUnix <= toDateTime64(1753328911,3)\n    AND MetricName = 'gen_ai.usage.cost'\n    AND ServiceName = 'chatterbox-api'\nGROUP BY time, ServiceName, MetricName\nORDER BY time",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Total Gen.AI Input Tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, max(Value) FROM $table WHERE $timeFilter \nAND MetricName = 'gen_ai.usage.input_tokens'\nGROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, max(Value) FROM base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1753285118,3) AND TimeUnix <= toDateTime64(1753286918,3) \nAND MetricName = 'gen_ai.usage.input_tokens'\nGROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Models",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--select SpanAttributes['gen_ai.request.model'] as model,SpanAttributes['gen_ai.request.temperature'] as temperature,  Count() as count from $table\nselect SpanAttributes['gen_ai.request.model'] as model, Count() as count from $table\n\nwhere $timeFilter\nand ServiceName = 'chatterbox-api'\ngroup by model --, temperature\norder by count DESC --, temperature DESC",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\n\nselect SpanAttributes['gen_ai.request.model'] as model, Count() as count from base14.otel_traces\n\nwhere Timestamp >= toDateTime64(1753304224,3) AND Timestamp <= toDateTime64(1753325824,3)\nand ServiceName = 'chatterbox-api'\ngroup by model \norder by count DESC ",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Avg Duration Per Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    $timeSeries AS time,\n    sum(Sum)/sum(Count) AS duration_per_call,\n    ServiceName,\n    MetricName\nFROM $table\nWHERE \n    $timeFilter\n    AND MetricName = 'gen_ai.client.operation.duration'\n    AND ServiceName = 'chatterbox-api'\nGROUP BY time, ServiceName, MetricName\nORDER BY time",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT \n    (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) AS time,\n    sum(Sum)/sum(Count) AS duration_per_call,\n    ServiceName,\n    MetricName\nFROM base14.otel_metrics_histogram\nWHERE \n    TimeUnix >= toDateTime64(1753317673,3) AND TimeUnix <= toDateTime64(1753321273,3)\n    AND MetricName = 'gen_ai.client.operation.duration'\n    AND ServiceName = 'chatterbox-api'\nGROUP BY time, ServiceName, MetricName\nORDER BY time",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Token Usage Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Count, Sum)\nFROM otel_metrics_histogram\nWHERE \n    $timeFilter\n    AND MetricName = 'gen_ai.client.token.usage'\n    AND ServiceName = 'chatterbox-api'\n",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond, if(max_1 - lagInFrame(max_1,1,0) OVER () < 0, nan, (max_1 - lagInFrame(max_1,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_1_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Count) AS max_0, max(Sum) AS max_1 FROM otel_metrics_histogram\nWHERE TimeUnix >= toDateTime64(1753286845,3) AND TimeUnix <= toDateTime64(1753290445,3) AND \n    TimeUnix >= toDateTime64(1753286845,3) AND TimeUnix <= toDateTime64(1753290445,3)\n    AND MetricName = 'gen_ai.client.token.usage'\n    AND ServiceName = 'chatterbox-api' GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Cost Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Count, Sum)\nFROM otel_metrics_histogram\nWHERE \n    $timeFilter\n    AND MetricName = 'gen_ai.usage.cost'\n    AND ServiceName = 'chatterbox-api'\n",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond, if(max_1 - lagInFrame(max_1,1,0) OVER () < 0, nan, (max_1 - lagInFrame(max_1,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_1_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Count) AS max_0, max(Sum) AS max_1 FROM otel_metrics_histogram\nWHERE TimeUnix >= toDateTime64(1753287642,3) AND TimeUnix <= toDateTime64(1753291242,3) AND \n    TimeUnix >= toDateTime64(1753287642,3) AND TimeUnix <= toDateTime64(1753291242,3)\n    AND MetricName = 'gen_ai.usage.cost'\n    AND ServiceName = 'chatterbox-api' GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Recent Prompts",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select toDateTime(Timestamp) as Time, SpanAttributes['gen_ai.prompt'] as Prompt from $table\nwhere $timeFilter\nand ServiceName = 'chatterbox-api'\norder by Timestamp DESC",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nselect toDateTime(Timestamp) as Time, SpanAttributes['gen_ai.prompt'] as Prompt from base14.otel_traces\nwhere Timestamp >= toDateTime64(1753320330,3) AND Timestamp <= toDateTime64(1753323930,3)\nand ServiceName = 'chatterbox-api'\norder by Timestamp DESC",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Token Usage by Prompts",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select SpanAttributes['gen_ai.prompt'] as Prompt, toInt64OrZero(SpanAttributes['gen_ai.client.token.usage']) as TokenUsage  from $table\nwhere $timeFilter\nand ServiceName = 'chatterbox-api'\norder by TokenUsage DESC",
     "rawQuery": "/* grafana dashboard='LLM Usage', user='4' */\nselect SpanAttributes['gen_ai.prompt'] as Prompt, toInt64OrZero(SpanAttributes['gen_ai.client.token.usage']) as TokenUsage  from base14.otel_traces\nwhere Timestamp >= toDateTime64(1753320477,3) AND Timestamp <= toDateTime64(1753324077,3)\nand ServiceName = 'chatterbox-api'\norder by TokenUsage DESC",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  }
 ]
}