{
 "title": "Metrics Catalog",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT DISTINCT ServiceName\nFROM (\n\tSELECT ServiceName\n\tFROM base14.otel_metrics_sum\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_gauge\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_summary\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_histogram\n\tWHERE TimeUnix > now() - interval 1 hour\n)\nORDER BY ServiceName"
   },
   { "name": "searchText", "label": "Metric Name Search" },
   {
    "name": "metricName",
    "label": "Metric",
    "query": "SELECT DISTINCT MetricName\nFROM (\n    SELECT MetricName \n\tFROM base14.otel_metrics_gauge \n   \tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n    \n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_sum\n\tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n    \n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_summary\n\tWHERE ServiceName in ($service)\n    AND TimeUnix > now() - interval 1 hour\n\t\n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_histogram\n\tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n) AS all_metrics\nORDER BY MetricName"
   }
  ]
 },
 "panels": [
  {
   "title": "Unique Metrics by Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    Service,\n    sum(NumMetrics) as TotalNumMetrics\nFROM (\n    -- From the sum table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_sum\n    WHERE $timeFilter\n    AND ServiceName in ($service)\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the gauge table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_gauge\n    WHERE $timeFilter\n        AND ServiceName in ($service)\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the summary table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_summary\n    WHERE $timeFilter\n        AND ServiceName in ($service)\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the histogram table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_histogram\n    WHERE $timeFilter\n        AND ServiceName in ($service)\n\n    GROUP BY Service\n) as combined\nGROUP BY Service\nORDER BY TotalNumMetrics DESC",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\n    Service,\n    sum(NumMetrics) as TotalNumMetrics\nFROM (\n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_sum\n    WHERE TimeUnix >= toDateTime64(1741650384, 3) AND TimeUnix <= toDateTime64(1741671984, 3)\n    AND ServiceName in ('')\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_gauge\n    WHERE TimeUnix >= toDateTime64(1741650384, 3) AND TimeUnix <= toDateTime64(1741671984, 3)\n        AND ServiceName in ('')\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_summary\n    WHERE TimeUnix >= toDateTime64(1741650384, 3) AND TimeUnix <= toDateTime64(1741671984, 3)\n        AND ServiceName in ('')\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_histogram\n    WHERE TimeUnix >= toDateTime64(1741650384, 3) AND TimeUnix <= toDateTime64(1741671984, 3)\n    \n    GROUP BY Service\n) as combined\nGROUP BY Service\nORDER BY TotalNumMetrics DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "All Metrics by Type",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    MetricName,\n    groupArray(TableName) as Tables\nFROM (\n    -- From the sum table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_sum' as TableName\n    FROM otel_metrics_sum\n    WHERE $timeFilter\n    AND ServiceName in ($service)\n           AND MetricName ilike '%${searchText:raw}%'\n\n    UNION ALL\n    \n    -- From the gauge table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_gauge' as TableName\n    FROM otel_metrics_gauge\n    WHERE $timeFilter\n       AND ServiceName in ($service)\n       AND MetricName ilike '%${searchText:raw}%'\n\n    UNION ALL\n    \n    -- From the summary table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_summary' as TableName\n    FROM otel_metrics_summary\n    WHERE $timeFilter\n    AND ServiceName in ($service)   \n           AND MetricName ilike '%${searchText:raw}%'\n    UNION ALL\n    \n    -- From the histogram table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_histogram' as TableName \n    FROM otel_metrics_histogram\n    WHERE $timeFilter\n       AND ServiceName in ($service)\n              AND MetricName ilike '%${searchText:raw}%'\n\n) as all_metrics\nGROUP BY MetricName\nORDER BY MetricName ASC",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2 Copy', user='2' */\nSELECT\n    MetricName,\n    groupArray(TableName) as Tables\nFROM (\n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_sum' as TableName\n    FROM otel_metrics_sum\n    WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\n    AND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\n           AND MetricName ilike '%queries%'\n\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_gauge' as TableName\n    FROM otel_metrics_gauge\n    WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\n       AND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\n       AND MetricName ilike '%queries%'\n\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_summary' as TableName\n    FROM otel_metrics_summary\n    WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\n    AND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')   \n           AND MetricName ilike '%queries%'\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_histogram' as TableName \n    FROM otel_metrics_histogram\n    WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\n       AND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\n              AND MetricName ilike '%queries%'\n\n) as all_metrics\nGROUP BY MetricName\nORDER BY MetricName ASC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Last 5 Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nand ServiceName in ($service)\nand MetricName = $metricName\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='2' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_sum where TimeUnix >= toDateTime64(1751306860,3) AND TimeUnix <= toDateTime64(1751310460,3)\nand ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\nand MetricName = 'chi_clickhouse_event_AggregationHashTablesInitializedAsTwoLevel'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nand ServiceName in ($service)\nand MetricName = $metricName\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='2' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1751306860,3) AND TimeUnix <= toDateTime64(1751310460,3)\nand ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\nand MetricName = 'chi_clickhouse_event_AggregationHashTablesInitializedAsTwoLevel'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nand ServiceName in ($service)\nand MetricName = $metricName\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='2' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_summary where TimeUnix >= toDateTime64(1751306860,3) AND TimeUnix <= toDateTime64(1751310460,3)\nand ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\nand MetricName = 'chi_clickhouse_event_AggregationHashTablesInitializedAsTwoLevel'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_summary"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nand ServiceName in ($service)\nand MetricName = $metricName\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2 Copy', user='2' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_histogram where TimeUnix >= toDateTime64(1751306987,3) AND TimeUnix <= toDateTime64(1751310587,3)\nand ServiceName in ()\nand MetricName = 'chi_clickhouse_event_AggregationHashTablesInitializedAsTwoLevel'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Plot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, avg(Value) FROM $table WHERE $timeFilter\nAND ServiceName in ($service)\nAND MetricName = $metricName\n GROUP BY t ORDER BY t\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2 Copy', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, avg(Value) FROM base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\nAND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\nAND MetricName = 'chi_clickhouse_event_ArenaAllocBytes'\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, avg(Value) FROM $table WHERE $timeFilter\nAND ServiceName in ($service)\nAND MetricName = $metricName\n GROUP BY t ORDER BY t\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2 Copy', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, avg(Value) FROM base14.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1751307011,3) AND TimeUnix <= toDateTime64(1751310611,3)\nAND ServiceName in ('ayoconnect-grafana','ayoconnect-otel','b14-003-hz-mk8s','base1-clickhouse','bureau-grafana','bureau-otel','cloudcosmos-grafana','cloudcosmos-otel','dmart-grafana','dmart-otel','dpd0-grafana','dpd0-otel','glomopay-grafana','glomopay-otel','greyamp-grafana','greyamp-otel','healthtap-grafana','healthtap-otel','kolo-grafana','kolo-otel','kulu-grafana','kulu-otel','liveheats-grafana','liveheats-otel','peach-grafana','peach-otel','pratilipi-grafana','pratilipi-otel','probe42-grafana','probe42-otel','quintype-grafana','quintype-otel','scout-collector','zinc-grafana','zinc-otel')\nAND MetricName = 'chi_clickhouse_event_ArenaAllocBytes'\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}