{
 "title": "Metrics Collected v2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "SELECT distinct ResourceAttributes['environment']\nFROM $table \nWHERE TimeUnix > now() - interval 1 hour"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "SELECT DISTINCT ServiceName\nFROM (\n\tSELECT ServiceName\n\tFROM base14.otel_metrics_sum\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_gauge\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_summary\n\tWHERE TimeUnix > now() - interval 1 hour\n\n\tUNION ALL\n\n\tSELECT ServiceName \n\tFROM base14.otel_metrics_histogram\n\tWHERE TimeUnix > now() - interval 1 hour\n)\nORDER BY ServiceName"
    }
   },
   {
    "name": "metricName",
    "label": "Metric",
    "query": {
     "query": "SELECT DISTINCT MetricName\nFROM (\n    SELECT MetricName \n\tFROM base14.otel_metrics_gauge \n   \tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n    \n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_sum\n\tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n    \n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_summary\n\tWHERE ServiceName in ($service)\n    AND TimeUnix > now() - interval 1 hour\n\t\n\tUNION ALL\n    \n\tSELECT MetricName \n\tFROM base14.otel_metrics_histogram\n\tWHERE ServiceName in ($service)\n\tAND TimeUnix > now() - interval 1 hour\n) AS all_metrics\nORDER BY MetricName"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unique Metrics by Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    Service,\n    sum(NumMetrics) as TotalNumMetrics\nFROM (\n    -- From the sum table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_sum\n    WHERE $timeFilter\n    AND ServiceName in (${service:singlequote})\n    AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the gauge table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_gauge\n    WHERE $timeFilter\n        AND ServiceName in (${service:singlequote})\n        AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the summary table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_summary\n    WHERE $timeFilter\n        AND ServiceName in (${service:singlequote})\n        AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    -- From the histogram table\n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_histogram\n    WHERE $timeFilter\n        AND ServiceName in (${service:singlequote})\n        AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    GROUP BY Service\n) as combined\nGROUP BY Service\nORDER BY TotalNumMetrics DESC",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\nSELECT\n    Service,\n    sum(NumMetrics) as TotalNumMetrics\nFROM (\n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_sum\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n    AND ServiceName in ('ecs','otelcol-contrib')\n    AND ResourceAttributes['environment'] = 'staging'\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_gauge\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n        AND ServiceName in ('ecs','otelcol-contrib')\n        AND ResourceAttributes['environment'] = 'staging'\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_summary\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n        AND ServiceName in ('ecs','otelcol-contrib')\n        AND ResourceAttributes['environment'] = 'staging'\n\n    GROUP BY Service\n    \n    UNION ALL\n    \n    \n    SELECT \n        distinct(ServiceName) as Service, \n        count(distinct(MetricName)) as NumMetrics \n    FROM base14.otel_metrics_histogram\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n        AND ServiceName in ('ecs','otelcol-contrib')\n        AND ResourceAttributes['environment'] = 'staging'\n\n    GROUP BY Service\n) as combined\nGROUP BY Service\nORDER BY TotalNumMetrics DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "All Metrics by Type",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    MetricName,\n    groupArray(TableName) as Tables\nFROM (\n    -- From the sum table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_sum' as TableName\n    FROM otel_metrics_sum\n    WHERE $timeFilter\n    AND ServiceName in (${service:singlequote})\n    AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    UNION ALL\n    \n    -- From the gauge table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_gauge' as TableName\n    FROM otel_metrics_gauge\n    WHERE $timeFilter\n    AND ServiceName in (${service:singlequote})\n    AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    UNION ALL\n    \n    -- From the summary table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_summary' as TableName\n    FROM otel_metrics_summary\n    WHERE $timeFilter\n    AND ServiceName in (${service:singlequote})\n    AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n    UNION ALL\n    \n    -- From the histogram table\n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_histogram' as TableName \n    FROM otel_metrics_histogram\n    WHERE $timeFilter\n    AND ServiceName in (${service:singlequote})\n    AND ResourceAttributes['environment'] = ${environment:singlequote}\n\n) as all_metrics\nGROUP BY MetricName\nORDER BY MetricName ASC",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\nSELECT\n    MetricName,\n    groupArray(TableName) as Tables\nFROM (\n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_sum' as TableName\n    FROM otel_metrics_sum\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n    AND ServiceName in ('ecs','otelcol-contrib')\n    AND ResourceAttributes['environment'] = 'staging'\n\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_gauge' as TableName\n    FROM otel_metrics_gauge\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n    AND ServiceName in ('ecs','otelcol-contrib')\n    AND ResourceAttributes['environment'] = 'staging'\n\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_summary' as TableName\n    FROM otel_metrics_summary\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n    AND ServiceName in ('ecs','otelcol-contrib')\n    AND ResourceAttributes['environment'] = 'staging'\n\n    UNION ALL\n    \n    \n    SELECT \n        distinct(MetricName) as MetricName,\n        'otel_metrics_histogram' as TableName \n    FROM otel_metrics_histogram\n    WHERE TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\n    AND ServiceName in ('ecs','otelcol-contrib')\n    AND ResourceAttributes['environment'] = 'staging'\n\n) as all_metrics\nGROUP BY MetricName\nORDER BY MetricName ASC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Last 5 Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_sum where TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\nAND ServiceName in ('ecs','otelcol-contrib')\nAND MetricName = 'container.blockio.io_service_bytes_recursive'\nAND ResourceAttributes['environment'] = 'staging'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\nAND ServiceName in ('ecs','otelcol-contrib')\nAND MetricName = 'container.blockio.io_service_bytes_recursive'\nAND ResourceAttributes['environment'] = 'staging'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_summary where TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\nAND ServiceName in ('ecs','otelcol-contrib')\nAND MetricName = 'container.blockio.io_service_bytes_recursive'\nAND ResourceAttributes['environment'] = 'staging'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_summary"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "--SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\n\nselect TimeUnix as EntryTime, * from $table where $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\norder by TimeUnix DESC LIMIT 5\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='3' */\n\n\nselect TimeUnix as EntryTime, * from base14.otel_metrics_histogram where TimeUnix >= toDateTime64(1752764653,3) AND TimeUnix <= toDateTime64(1752768253,3)\nAND ServiceName in ('ecs','otelcol-contrib')\nAND MetricName = 'container.blockio.io_service_bytes_recursive'\nAND ResourceAttributes['environment'] = 'staging'\norder by TimeUnix DESC LIMIT 5",
     "round": "0s",
     "table": "otel_metrics_histogram"
    }
   ]
  },
  {
   "title": "Plot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, avg(Value) FROM $table WHERE $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\n GROUP BY t ORDER BY t\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='5' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) as t, avg(Value) FROM base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1753348210,3) AND TimeUnix <= toDateTime64(1753351810,3)\nAND ServiceName in ('appstatus/bakasura/proxy','appstatus/bender','appstatus/devops/flower','appstatus/devops/grafana','appstatus/devops/pgadmin','appstatus/devops/sonarqube','appstatus/devops/vault','appstatus/finmo/alb','appstatus/finmo/api','appstatus/finmo/app','appstatus/finmo/bheema','appstatus/finmo/webhooks','appstatus/hg','appstatus/tara','awsfirehose/metrics','github','otelcol-contrib','postgres/app-finmo-db','rabbitmq/app-finmo-rabbitmq','redis/app-finmo-redis')\nAND MetricName = 'AWS/ApplicationELB/ActiveConnectionCount'\nAND ResourceAttributes['environment'] = 'production'\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, avg(Value) FROM $table WHERE $timeFilter\nAND ServiceName in (${service:singlequote})\nAND MetricName = ${metricName:singlequote}\nAND ResourceAttributes['environment'] = ${environment:singlequote}\n GROUP BY t ORDER BY t\n",
     "rawQuery": "/* grafana dashboard='Metrics Collected v2', user='5' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) as t, avg(Value) FROM base14.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1753348210,3) AND TimeUnix <= toDateTime64(1753351810,3)\nAND ServiceName in ('appstatus/bakasura/proxy','appstatus/bender','appstatus/devops/flower','appstatus/devops/grafana','appstatus/devops/pgadmin','appstatus/devops/sonarqube','appstatus/devops/vault','appstatus/finmo/alb','appstatus/finmo/api','appstatus/finmo/app','appstatus/finmo/bheema','appstatus/finmo/webhooks','appstatus/hg','appstatus/tara','awsfirehose/metrics','github','otelcol-contrib','postgres/app-finmo-db','rabbitmq/app-finmo-rabbitmq','redis/app-finmo-redis')\nAND MetricName = 'AWS/ApplicationELB/ActiveConnectionCount'\nAND ResourceAttributes['environment'] = 'production'\n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}