{
 "title": "K8s Pods Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count(distinct ResourceAttributes['k8s.pod.uid']) FROM $table \nWHERE $timeFilter \nAND ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.phase'\nGROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, count(distinct ResourceAttributes['k8s.pod.uid']) FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) \nAND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.phase'\nGROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Pods by Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, Value, count(distinct(ResourceAttributes['k8s.pod.name']))\nFROM $table\nWHERE $timeFilter\nAND MetricName = 'k8s.pod.phase'\nAND ResourceAttributes['k8s.deployment.name'] == ''\nAND ResourceAttributes['k8s.statefulset.name'] == ''\nAND ResourceAttributes['k8s.daemonset.name'] == ''\nAND ResourceAttributes['k8s.namespace.name'] != 'kube-system'\nGROUP BY t, Value ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Pods by Phase (Current)",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, Value as Phase, count(distinct(ResourceAttributes['k8s.pod.name'])) as Pods\nFROM $table\nWHERE $timeFilter\nAND MetricName = 'k8s.pod.phase'\nAND ResourceAttributes['k8s.deployment.name'] == ''\nAND ResourceAttributes['k8s.statefulset.name'] == ''\nAND ResourceAttributes['k8s.daemonset.name'] == ''\nAND ResourceAttributes['k8s.namespace.name'] != 'kube-system'\nGROUP BY t, Phase\nORDER BY t, Phase ASC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Pods running by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.namespace.name'] Namespace, count(*) as NoOfPods)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.phase'\nGROUP BY t, Namespace ORDER BY t, NoOfPods",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((Namespace, NoOfPods)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.namespace.name'] Namespace, count(*) as NoOfPods FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.phase' GROUP BY t, Namespace ORDER BY t, NoOfPods) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Total Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 7 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.container.name'] container, anyLast(Value) c)\nFROM $table\nWHERE $timeFilter\nAND MetricName = 'k8s.container.restarts'",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Intensive Pods",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] as pod, max(Value)*1000 as CPUUtilisation)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.cpu.utilization'\nGROUP BY t, pod ORDER BY t, CPUUtilisation DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, CPUUtilisation)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] as pod, max(Value) * 1000 as CPUUtilisation FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.cpu.utilization' GROUP BY t, pod ORDER BY t, CPUUtilisation DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Memory Intensive Pods",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] as pod, max(Value) as MemoryUsage)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.memory.usage'\nGROUP BY t, pod ORDER BY t, MemoryUsage DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, MemoryUsage)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] as pod, max(Value) as MemoryUsage FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.memory.usage' GROUP BY t, pod ORDER BY t, MemoryUsage DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "CPU Intensive Pods",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] as pod, max(Value)*1000 as CPUUtilisation)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.cpu.utilization'\nGROUP BY t, pod ORDER BY t, CPUUtilisation DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, CPUUtilisation)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] as pod, max(Value) * 1000 as CPUUtilisation FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.cpu.utilization' GROUP BY t, pod ORDER BY t, CPUUtilisation DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Memory Intensive Pods",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] as pod, max(Value) as MemoryUsage)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'k8s.pod.memory.usage'\nGROUP BY t, pod ORDER BY t, MemoryUsage DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, MemoryUsage)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] as pod, max(Value) as MemoryUsage FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'k8s.pod.memory.usage' GROUP BY t, pod ORDER BY t, MemoryUsage DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Intensive Containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.container.name'] as pod, max(Value)*1000 as CPUUtilisation)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'container.cpu.utilization'\nGROUP BY t, pod ORDER BY t, CPUUtilisation DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, CPUUtilisation)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.container.name'] as pod, max(Value) * 1000 as CPUUtilisation FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'container.cpu.utilization' GROUP BY t, pod ORDER BY t, CPUUtilisation DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Memory Intensive Containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.container.name'] as pod, max(Value) as MemoryUsage)\nFROM $table\nWHERE ServiceName = 'k8s'\nAND MetricName = 'container.memory.usage'\nGROUP BY t, pod ORDER BY t, MemoryUsage DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT t, groupArray((pod, MemoryUsage)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, ResourceAttributes['k8s.container.name'] as pod, max(Value) as MemoryUsage FROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3) AND ServiceName = 'k8'\nAND MetricName = 'container.memory.usage' GROUP BY t, pod ORDER BY t, MemoryUsage DESC) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container,  anyLast(Value) Status\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'k8s.container.ready'\nGROUP BY Container ORDER BY Status DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container,  anyLast(Value) Status\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'k8s.container.ready'\nGROUP BY Container ORDER BY Status DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container, max(Value)*1000 as CPUUtilisation\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'container.cpu.utilization'\nGROUP BY Container ORDER BY CPUUtilisation DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container, max(Value)*1000 as CPUUtilisation\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'container.cpu.utilization'\nGROUP BY Container ORDER BY CPUUtilisation DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as MemoryRSS\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'container.memory.rss'\nGROUP BY Container ORDER BY MemoryRSS DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as MemoryRSS\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'container.memory.rss'\nGROUP BY Container ORDER BY MemoryRSS DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as UsedDisk\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'container.filesystem.usage'\nGROUP BY Container ORDER BY UsedDisk DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as UsedDisk\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'container.filesystem.usage'\nGROUP BY Container ORDER BY UsedDisk DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as Restarts\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'k8s.container.restarts'\nGROUP BY Container ORDER BY Restarts DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container, max(Value) as Restarts\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'k8s.container.restarts'\nGROUP BY Container ORDER BY Restarts DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ResourceAttributes['k8s.container.name'] as Container, anyLast(ResourceAttributes['container.image.name']) Image\nFROM $table\nWHERE $timeFilter\nAND ServiceName = 'k8s'\nAND MetricName = 'k8s.container.ready'\nGROUP BY Container ORDER BY Image DESC",
     "rawQuery": "/* grafana dashboard=K8s Pods Overview v2, user=9 */\nSELECT ResourceAttributes['k8s.container.name'] as Container, anyLast(ResourceAttributes['container.image.name']) Image\nFROM base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1747715753, 3) AND TimeUnix <= toDateTime64(1747719353, 3)\nAND ServiceName = 'k8'\nAND MetricName = 'k8s.container.ready'\nGROUP BY Container ORDER BY Image DESC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}