{
 "title": "Clichouse Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "SELECT distinct Attributes['hostname']  FROM otel_metrics_gauge_local where ServiceName='clickhouse' and MetricName='chi_clickhouse_metric_Uptime' "
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "system",
     "dateTimeColDataType": "event_time_microseconds",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "-- Outermost query: Calculates rate of queries\nSELECT\n    t,  -- Timestamp (binned)\n    arrayMap(a -> (a.1, a.2 / runningDifference(t / 1000)), groupArr)\n    -- Transforms grouped data, calculating a rate/difference\n\nFROM (\n    -- Middle query: Groups queries by timestamp\n    SELECT \n        t, \n        groupArray((q, c)) AS groupArr\n    \n    FROM (\n        -- Inner (lowest) query: Fetches and preprocesses query log data\n        SELECT\n            (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t,  -- Time binning\n            normalizeQuery(query) AS q,  -- Normalize queries\n            count() c  -- Count queries\n        FROM cluster('default', system.query_log)\n        \n        -- Multiple conditional filters:\n        WHERE $timeFilter\n --       AND (\n --           ('$type' = '1,2,3,4' AND type != 'QueryStart') \n --           OR \n --           ('$type' != '1,2,3,4' AND type IN ($type))\n --       )\n        -- Conditional tests for query kind, user, duration\n  --      $conditionalTest(AND query_kind IN ($query_kind), $query_kind)\n--        $conditionalTest(AND initial_user IN ($user), $user)\n        AND query_duration_ms >= 500\n        AND query_duration_ms <= 100000\n        \n        -- Subquery to filter most frequent query hashes\n        AND normalized_query_hash GLOBAL IN (\n            SELECT \n                normalized_query_hash AS h\n            FROM cluster('default', system.query_log)\n            -- Similar filtering conditions as above\n            WHERE $timeFilter\n            -- ... (similar filtering)\n            GROUP BY h\n            ORDER BY count() DESC\n            LIMIT 100\n            SETTINGS skip_unavailable_shards=1\n        )\n        \n        GROUP BY t, query\n        ORDER BY t\n    )\n    \n    GROUP BY t\n    ORDER BY t\n) \n",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\n\nSELECT\n    t,  \n    arrayMap(a -> (a.1, a.2 / runningDifference(t / 1000)), groupArr)\n    \n\nFROM (\n    \n    SELECT \n        t, \n        groupArray((q, c)) AS groupArr\n    \n    FROM (\n        \n        SELECT\n            (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t,  \n            normalizeQuery(query) AS q,  \n            count() c  \n        FROM cluster('default', system.query_log)\n        \n        \n        WHERE event_time_microseconds >= toDateTime64(1734532335, 3) AND event_time_microseconds <= toDateTime64(1734543135, 3)\n \n \n \n \n \n        \n  \n\n        AND query_duration_ms >= 00\n        AND query_duration_ms <= 100000\n        \n        \n        AND normalized_query_hash GLOBAL IN (\n            SELECT \n                normalized_query_hash AS h\n            FROM cluster('default', system.query_log)\n            \n            WHERE event_time_microseconds >= toDateTime64(1734532335, 3) AND event_time_microseconds <= toDateTime64(1734543135, 3)\n            \n            GROUP BY h\n            ORDER BY count() DESC\n            LIMIT 100\n            SETTINGS skip_unavailable_shards=1\n        )\n        \n        GROUP BY t, query\n        ORDER BY t\n    )\n    \n    GROUP BY t\n    ORDER BY t\n)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Uptime $hostname",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    ServiceName,\n    MetricName,\n    TimeUnix,\n    Value\nFROM $table\nWHERE \n    MetricName = 'chi_clickhouse_metric_Uptime'\n    AND Attributes['hostname'] LIKE '$unescape($hostname)'\nORDER BY TimeUnix DESC limit 1",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT \n    ServiceName,\n    MetricName,\n    TimeUnix,\n    Value\nFROM default.otel_metrics_gauge\nWHERE \n    MetricName = 'chi_clickhouse_metric_Uptime'\n    AND Attributes['hostname'] LIKE 'chi-clickhouse-default-3-0.default.svc.cluster.local'\nORDER BY TimeUnix DESC limit",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Memory for Queries $hostname",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryTracking'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) as t, Value FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734522221, 3) AND TimeUnix <= toDateTime64(1734543821, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryTracking'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Memory Stats $hostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as MemoryCode FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryCode'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as  FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540374, 3) AND TimeUnix <= toDateTime64(1734543974, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryCode'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as MemoryResident FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryResident'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as  FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540374, 3) AND TimeUnix <= toDateTime64(1734543974, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryResident'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as MemoryShared FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryShared'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as  FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540374, 3) AND TimeUnix <= toDateTime64(1734543974, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryShared'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as MemoryDataAndStack FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryDataAndStack'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as  FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540374, 3) AND TimeUnix <= toDateTime64(1734543974, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryDataAndStack'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as MemoryVirtual FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryVirtual'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as  FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540374, 3) AND TimeUnix <= toDateTime64(1734543974, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryVirtual'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "Disk Usage $hostname",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 43 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Memory Occupied $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as PrimaryKeyBytesAllocated FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryPrimaryKeyBytesAllocated'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) as t, Value as MemoryCode FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540881, 3) AND TimeUnix <= toDateTime64(1734544481, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryPrimaryKeyBytesAllocated'\nAND Attributes['hostname'] = 'chi-clickhouse-default-3-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as DictionaryBytesAllocated FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryDictionaryBytesAllocated'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, Value as MemoryResident FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734540881, 3) AND TimeUnix <= toDateTime64(1734544481, 3)\nAND ServiceName='clickhouse'\nAND MetricName='chi_clickhouse_metric_MemoryDictionaryBytesAllocated'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Connections $hostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "repeat": "hostname",
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as TCP FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_TCPConnection'\nAND Attributes['hostname'] = '$unescape($hostname)'\n\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, Value as TCPConnections FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734740380, 3) AND TimeUnix <= toDateTime64(1734742180, 3)\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_TCPConnection'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\n\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as HTTP FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_HTTPConnection'\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, Value as HTT FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734740380, 3) AND TimeUnix <= toDateTime64(1734742180, 3)\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_HTTPConnection'\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as InterServer FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_InterserverConnection'\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, Value as InterServe FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734740380, 3) AND TimeUnix <= toDateTime64(1734742180, 3)\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_metric_InterserverConnection'\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Parts $hostname",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 61 },
   "repeat": "hostname",
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value AS ActiveParts FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_table_parts' \nAND Attributes['active'] = '1'\nAND Attributes['hostname'] = '$unescape($hostname)'\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) as t, Value AS ActiveParts FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734522221, 3) AND TimeUnix <= toDateTime64(1734543821, 3)\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_table_parts' \nAND Attributes['active'] = '1'\nAND Attributes['hostname'] = 'chi-clickhouse-default-0-0.default.svc.cluster.local'\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Value as InactiveParts FROM $table WHERE\n$timeFilter\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_table_parts' \nAND Attributes['active'] = '0'\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Clichouse Monitor, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) as t, Value as InactiveParts' FROM default.otel_metrics_gauge WHERE\nTimeUnix >= toDateTime64(1734539612, 3) AND TimeUnix <= toDateTime64(1734543212, 3)\nAND ServiceName='clickhouse'\nAND MetricName = 'chi_clickhouse_table_parts' \nAND Attributes['active'] = '0'\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}