{
 "title": "OTel Collector Data Flow",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "SELECT distinct ServiceName FROM $table \nWHERE TimeUnix > now() - interval 12 hour\nand ServiceName like '%-otel'\norder by ServiceName \n"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "select distinct ResourceAttributes['environment'] from $table\nwhere $timeFilter \nand ServiceName = '$tenant'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, avg(Value)\nFROM $table \nWHERE $timeFilter \nAND MetricName = 'otelcol_process_memory_rss'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\nGROUP BY t\nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t, avg(Value)\nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752487157,3) AND TimeUnix <= toDateTime64(1752490757,3) \nAND MetricName = 'otelcol_process_memory_rss'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Accepted and Sent Spans per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_exporter_sent_spans'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_sent_spans'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_receiver_accepted_spans'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_accepted_spans'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Accepted : Spans Metrics and Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_receiver_accepted_spans'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_accepted_spans'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_receiver_accepted_metric_points'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_accepted_metric_points'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_receiver_accepted_log_records'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_accepted_log_records'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Sent : Spans Metrics and Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_exporter_sent_spans'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_sent_spans'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table\nWHERE $table.MetricName = 'otelcol_exporter_sent_metric_points'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_sent_metric_points'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value)\nFROM $table \nWHERE $table.MetricName = 'otelcol_exporter_sent_log_records'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, max(Value) AS max_0 FROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3) AND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_sent_log_records'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground' GROUP BY t ORDER BY t)",
     "round": "0",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Receiver Refused Spans Metrics and Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() AS RefusedSpans\nFROM $table\nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_receiver_refused_spans'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t \nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() AS RefusedSpans\nFROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_refused_spans'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t \nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() AS RefusedMetrics\nFROM $table\nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_receiver_refused_metric_points'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t\nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() AS RefusedMetrics\nFROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_refused_metric_points'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t\nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() AS RefusedLogs \nFROM $table\nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_receiver_refused_log_records'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t \nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() AS RefusedLogs \nFROM base14.otel_metrics_sum\nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_receiver_refused_log_records'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t \nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Sender Failed Spans Metrics and Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() as FailedSpans \nFROM $table \nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_exporter_send_failed_spans' \nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t \nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() as FailedSpans \nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_send_failed_spans' \nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t \nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() as FailedMetrics \nFROM $table \nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_exporter_send_failed_metric_points' \nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t \nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() as FailedMetrics \nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_send_failed_metric_points' \nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t \nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    },
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries t, count() AS FailedLogs \nFROM $table \nWHERE $timeFilter\nAND $table.MetricName = 'otelcol_exporter_send_failed_log_records'\nAND ServiceName in '$tenant'\nAND ResourceAttributes['environment'] = '${env:raw}'\n\nGROUP BY t \nORDER BY t",
     "rawQuery": "/* grafana dashboard='OTel Collector Data Flow', user='2' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, count() AS FailedLogs \nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752487648,3) AND TimeUnix <= toDateTime64(1752491248,3)\nAND base14.otel_metrics_sum.MetricName = 'otelcol_exporter_send_failed_log_records'\nAND ServiceName in 'dmart-otel'\nAND ResourceAttributes['environment'] = 'playground'\n\nGROUP BY t \nORDER BY t",
     "round": "0",
     "table": "otel_metrics_sum"
    }
   ]
  }
 ]
}