{
 "title": "LogStats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Unique Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B+$C+$D", "type": "math" }
   ]
  },
  {
   "title": "Logs By Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT  if(ResourceAttributes['k8s.pod.name'] != '',ResourceAttributes['k8s.pod.name'], ResourceAttributes['host.name'])  as Pod,  count() LogCount FROM $table WHERE $timeFilter \nGROUP BY Pod\nOrder by LogCount desc\n",
     "rawQuery": "/* grafana dashboard=LogStats, user=1 */\nSELECT  if(ResourceAttributes['k8s.pod.name'] != '',ResourceAttributes['k8s.pod.name'], ResourceAttributes['host.name']  as Pod,  count() LogCount FROM base14.otel_logs WHERE Timestamp >= toDateTime64(1736202454, 3) AND Timestamp <= toDateTime64(1736224054, 3) \nGROUP BY Pod\nOrder by LogCount desc",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  },
  {
   "title": "Logs By Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT  if(ServiceName != '', ServiceName, ResourceAttributes['k8s.container.name']) as Service ,  count() LogCount FROM $table WHERE $timeFilter \nGROUP BY if(ServiceName != '', ServiceName, ResourceAttributes['k8s.container.name']) as Service\nOrder by LogCount desc\n",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT  if(ServiceName != '', ServiceName, ResourceAttributes['k8s.container.name']) as Service ,  count() LogCount FROM base14.otel_logs WHERE Timestamp >= toDateTime64(1736141114, 3) AND Timestamp <= toDateTime64(1736162714, 3) \nGROUP BY if(ServiceName != '', ServiceName, ResourceAttributes['k8s.container.name']) as Service\nOrder by LogCount des",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  },
  {
   "title": "Errors and Exceptions",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT  TimestampTime, Body from $table where $timeFilter\nAND multiSearchAny(Body, ['error', 'exception']) \nORDER BY TimestampTime\n\n",
     "rawQuery": "/* grafana dashboard=LogStats, user=1 */\nSELECT  TimestampTime, Body from base14.otel_logs where Timestamp >= toDateTime64(1736202454, 3) AND Timestamp <= toDateTime64(1736224054, 3)\nAND \nORDER BY TimestampTime",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  }
 ]
}