{
 "title": "Host Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "SELECT DISTINCT ResourceAttributes['host.id'] as host\nFROM $table \nWHERE TimeUnix > now() - interval 1 hour\nORDER BY host"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Number of cpu cores used.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t,ResourceAttributes['host.id'] as host,  max(Value) Used \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'instance_cpu_usage_system'\nGROUP BY t, host",
     "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) as t,ResourceAttributes['host.id'] as host,  max(Value) Used \nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752740840,3) AND TimeUnix <= toDateTime64(1752742640,3) \nAND MetricName = 'instance_cpu_usage_system'\nGROUP BY t, host",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Active TCP Connections",
   "type": "gauge",
   "description": "Number of established connections.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n   $timeSeries as t, \n    ResourceAttributes['host.id'] as host,\n    max(Value),\nFROM $table \nWHERE $timeFilter\n    AND MetricName = 'system.network.connections'  \n    AND Attributes['protocol'] = 'tcp'\n    AND Attributes['state'] = 'ESTABLISHED'\nGROUP BY host, t",
     "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT\n   (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, \n    ResourceAttributes['host.id'] as host,\n    max(Value),\nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752740840,3) AND TimeUnix <= toDateTime64(1752742640,3)\n    AND MetricName = 'system.network.connections'  \n    AND Attributes['protocol'] = 'tcp'\n    AND Attributes['state'] = 'ESTABLISHED'\nGROUP BY host, t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Physical RAM actively in use by applications and system processes. Excludes easily reclaimable cache memory.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t,ResourceAttributes['host.id'] as host,  max(Value) Used \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'instance_memory_utilization' \nGROUP BY t, host",
     "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t,ResourceAttributes['host.id'] as host,  max(Value) Used \nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752740840,3) AND TimeUnix <= toDateTime64(1752742640,3) \nAND MetricName = 'instance_memory_utilization' \nGROUP BY t, host",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) LoadAvg15Min \nFROM $table \nWHERE $timeFilter\nAND MetricName = 'system.cpu.load_average.15m' \nAND ResourceAttributes['host.id'] ='$host'\nGROUP BY t \nORDER BY t",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) LoadAvg15Min \nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.cpu.load_average.15m' \nAND ResourceAttributes['host.id'] ='i-0fd3a57095204b2ba'\nGROUP BY t \nORDER BY t",
       "round": "0s",
       "table": "otel_metrics_gauge"
      },
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) LoadAvg5Min \nFROM $table \nWHERE $timeFilter\nAND MetricName = 'system.cpu.load_average.5m' \nAND ResourceAttributes['host.id'] ='$host'\nGROUP BY t \nORDER BY t",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) LoadAvg5Min \nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.cpu.load_average.5m' \nAND ResourceAttributes['host.id'] ='i-0fd3a57095204b2ba'\nGROUP BY t \nORDER BY t",
       "round": "0s",
       "table": "otel_metrics_gauge"
      },
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) LoadAvg1Min \nFROM $table \nWHERE $timeFilter\nAND MetricName = 'system.cpu.load_average.1m' \nAND ResourceAttributes['host.id'] ='$host'\nGROUP BY t \nORDER BY t",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) LoadAvg1Min \nFROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.cpu.load_average.1m' \nAND ResourceAttributes['host.id'] ='i-0fd3a57095204b2ba'\nGROUP BY t \nORDER BY t",
       "round": "0s",
       "table": "otel_metrics_gauge"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) Used\nFROM $table \nWHERE $timeFilter \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] = ${host:singlequote}\nAND Attributes['state'] = 'used'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) Used\nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8'\nAND Attributes['state'] = 'used'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "round": "0s",
       "table": "otel_metrics_sum"
      },
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) Cached\nFROM $table \nWHERE $timeFilter \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] in (${host:singlequote})\nAND Attributes['state'] = 'cached'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) Cached\nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] in ('i-0ebf0d72e0e005cf8')\nAND Attributes['state'] = 'cached'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "round": "0s",
       "table": "otel_metrics_sum"
      },
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT $timeSeries as t, max(Value) Free\nFROM $table \nWHERE $timeFilter \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] in (${host:singlequote})\nAND Attributes['state'] = 'free'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, max(Value) Free\nFROM base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) \nAND MetricName = 'system.memory.usage' \nAND ResourceAttributes['host.id'] in ('i-0ebf0d72e0e005cf8')\nAND Attributes['state'] = 'free'\nGROUP BY t, ResourceAttributes['host.id']\nORDER BY t, ResourceAttributes['host.id']",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLast(Value) c) \nfrom $table \nwhere $timeFilter\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = ${host:singlequote}\nAND Attributes['state'] = 'free'\nGROUP BY t, device\nORDER BY t, device",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['device'] device, anyLast(Value) c from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8'\nAND Attributes['state'] = 'free' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLast(Value) c) \nfrom $table \nwhere $timeFilter\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = ${host:singlequote}\nAND Attributes['state'] = 'used'\nGROUP BY t, device\nORDER BY t, device",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['device'] device, anyLast(Value) c from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8'\nAND Attributes['state'] = 'used' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Disk Reserved",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLast(Value) c) \nfrom $table \nwhere $timeFilter\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = ${host:singlequote}\nAND Attributes['state'] = 'reserved'\nGROUP BY t, device\nORDER BY t, device",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['device'] device, anyLast(Value) c from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.filesystem.usage'\nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8'\nAND Attributes['state'] = 'reserved' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['state'] state, anyLastIf(Value, Attributes['protocol'] == 'tcp') c) \nfrom $table \nwhere $timeFilter\nAND ResourceAttributes['host.id'] = ${host:singlequote}\nAND MetricName = 'system.network.connections' \nGROUP BY t, state\nORDER BY t, state",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((state, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['state'] state, anyLastIf(Value, Attributes['protocol'] == 'tcp') c from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8'\nAND MetricName = 'system.network.connections'  GROUP BY t, state ORDER BY t, state) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Network I/O (receive)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c) \nfrom $table \nwhere $timeFilter\nAND MetricName = 'system.network.io' \nAND ResourceAttributes['host.id'] = ${host:singlequote}\nGROUP BY t, device\nORDER BY t, device",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.network.io' \nAND ResourceAttributes['host.id'] = 'i-0ebf0d72e0e005cf8' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Network I/O (transmit)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c) from $table where $timeFilter\nAND MetricName = 'system.network.io' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.network.io' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Packets dropped (receive)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c) from $table where $timeFilter\nAND MetricName = 'system.network.dropped' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.network.dropped' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Packets dropped (transmit)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c) from $table where $timeFilter\nAND MetricName = 'system.network.dropped' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.network.dropped' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Network Errors (receive)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c) from $table where $timeFilter\nAND MetricName = 'system.network.errors' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'receive') c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.network.errors' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Network Errors (transmit)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c) from $table where $timeFilter\nAND MetricName = 'system.network.errors' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((device, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['device'] device, anyLastIf(Value, Attributes['direction'] == 'transmit') c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.network.errors' GROUP BY t, device ORDER BY t, device) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(Attributes['status'] status, anyLast(Value) c) from $table where $timeFilter\nAND MetricName = 'system.processes.count' ",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, groupArray((status, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, Attributes['status'] status, anyLast(Value) c from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3) AND TimeUnix >= toDateTime64(1752733315,3) AND TimeUnix <= toDateTime64(1752735115,3)\nAND MetricName = 'system.processes.count' GROUP BY t, status ORDER BY t, status) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    },
    {
     "title": "Processes Created per second",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "base14",
       "dateTimeColDataType": "TimeUnix",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$perSecond(Value) from $table where $timeFilter\nAND MetricName = 'system.processes.created'  AND ResourceAttributes['host.id'] = ${host:singlequote}\n\n",
       "rawQuery": "/* grafana dashboard='Host Metrics', user='3' */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, max(Value) AS max_0 from base14.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3) AND TimeUnix >= toDateTime64(1752733531,3) AND TimeUnix <= toDateTime64(1752735331,3)\nAND MetricName = 'system.processes.created'  AND ResourceAttributes['host.id'] = 'i-0fd3a57095204b2ba' GROUP BY t ORDER BY t)",
       "round": "0s",
       "table": "otel_metrics_sum"
      }
     ]
    }
   ]
  }
 ]
}