{
 "title": "Client Activity",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Clients - Production",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nWITH telemetry_data AS (\n    SELECT \n        ServiceName,\n        MetricName,\n        argMin(Value, TimeUnix) as first_value,\n        argMax(Value, TimeUnix) as last_value,\n        argMax(Value, TimeUnix) - argMin(Value, TimeUnix) as delta_count  -- Delta for counter metrics\n    FROM base14.otel_metrics_sum\n    WHERE ServiceName LIKE '%-otel'  -- Services ending with 'otel'\n        AND $timeFilter\n        AND MetricName IN (\n            'otelcol_receiver_accepted_log_records',\n            'otelcol_receiver_accepted_metric_points', \n            'otelcol_receiver_accepted_spans'\n        )\n        AND ResourceAttributes['environment'] like '%production'\n    GROUP BY ServiceName, MetricName\n)\nSELECT \n    ServiceName,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_log_records' THEN delta_count ELSE 0 END) as Logs,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_metric_points' THEN delta_count ELSE 0 END) as Metrics,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_spans' THEN delta_count ELSE 0 END) as Traces,\n    sum(delta_count) as Total\nFROM telemetry_data\nGROUP BY ServiceName\nORDER BY Total DESC",
     "rawQuery": "/* grafana dashboard='Client Activity', user='2' */\nWITH telemetry_data AS (\n    SELECT \n        ServiceName,\n        MetricName,\n        argMin(Value, TimeUnix) as first_value,\n        argMax(Value, TimeUnix) as last_value,\n        argMax(Value, TimeUnix) - argMin(Value, TimeUnix) as delta_count  \n    FROM base14.otel_metrics_sum\n    WHERE ServiceName LIKE '%-otel'  \n        AND TimeUnix >= toDateTime64(1752237708,3) AND TimeUnix <= toDateTime64(1752241308,3)\n        AND MetricName IN (\n            'otelcol_receiver_accepted_log_records',\n            'otelcol_receiver_accepted_metric_points', \n            'otelcol_receiver_accepted_spans'\n        )\n        AND ResourceAttributes['environment'] like '%production'\n    GROUP BY ServiceName, MetricName\n)\nSELECT \n    ServiceName,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_log_records' THEN delta_count ELSE 0 END) as Logs,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_metric_points' THEN delta_count ELSE 0 END) as Metrics,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_spans' THEN delta_count ELSE 0 END) as Traces,\n    sum(delta_count) as Total\nFROM telemetry_data\nGROUP BY ServiceName\nORDER BY Total DESC",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Inactive Clients - Playground",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT DISTINCT ServiceName\nFROM base14.otel_metrics_gauge\nWHERE ServiceName LIKE '%-otel'\nAND TimeUnix > now() - interval 10 day\nAND ResourceAttributes['environment'] = 'playground'\nAND ServiceName NOT IN (\n    SELECT DISTINCT ServiceName\n    FROM $table\n    WHERE ServiceName LIKE '%-otel'\n    AND $timeFilter\n    AND MetricName = 'otelcol_processor_accepted_metric_points'\n    AND ResourceAttributes['environment'] = 'playground'\n)\nORDER BY ServiceName",
     "rawQuery": "/* grafana dashboard='Client Activity', user='2' */\nSELECT DISTINCT ServiceName\nFROM base14.otel_metrics_gauge\nWHERE ServiceName LIKE '%-otel'\nAND TimeUnix > now() - interval 10 day\nAND ResourceAttributes['environment'] = 'playground'\nAND ServiceName NOT IN (\n    SELECT DISTINCT ServiceName\n    FROM base14.otel_metrics_sum\n    WHERE ServiceName LIKE '%-otel'\n    AND TimeUnix >= toDateTime64(1752237708,3) AND TimeUnix <= toDateTime64(1752241308,3)\n    AND MetricName = 'otelcol_processor_accepted_metric_points'\n    AND ResourceAttributes['environment'] = 'playground'\n)\nORDER BY ServiceName",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Active Clients - Playground",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 7 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nWITH telemetry_data AS (\n    SELECT \n        ServiceName,\n        MetricName,\n        argMin(Value, TimeUnix) as first_value,\n        argMax(Value, TimeUnix) as last_value,\n        argMax(Value, TimeUnix) - argMin(Value, TimeUnix) as delta_count  -- Delta for counter metrics\n    FROM base14.otel_metrics_sum\n    WHERE ServiceName LIKE '%-otel'  -- Services ending with 'otel'\n        AND $timeFilter\n        AND MetricName IN (\n            'otelcol_receiver_accepted_log_records',\n            'otelcol_receiver_accepted_metric_points', \n            'otelcol_receiver_accepted_spans'\n        )\n        AND ResourceAttributes['environment'] = 'playground'\n\n    GROUP BY ServiceName, MetricName\n)\nSELECT \n    ServiceName,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_log_records' THEN delta_count ELSE 0 END) as Logs,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_metric_points' THEN delta_count ELSE 0 END) as Metrics,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_spans' THEN delta_count ELSE 0 END) as Traces,\n    sum(delta_count) as Total\nFROM telemetry_data\nGROUP BY ServiceName\nORDER BY Total DESC",
     "rawQuery": "/* grafana dashboard='Client Activity', user='2' */\nWITH telemetry_data AS (\n    SELECT \n        ServiceName,\n        MetricName,\n        argMin(Value, TimeUnix) as first_value,\n        argMax(Value, TimeUnix) as last_value,\n        argMax(Value, TimeUnix) - argMin(Value, TimeUnix) as delta_count  \n    FROM base14.otel_metrics_sum\n    WHERE ServiceName LIKE '%-otel'  \n        AND TimeUnix >= toDateTime64(1752237708,3) AND TimeUnix <= toDateTime64(1752241308,3)\n        AND MetricName IN (\n            'otelcol_receiver_accepted_log_records',\n            'otelcol_receiver_accepted_metric_points', \n            'otelcol_receiver_accepted_spans'\n        )\n        AND ResourceAttributes['environment'] = 'playground'\n\n    GROUP BY ServiceName, MetricName\n)\nSELECT \n    ServiceName,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_log_records' THEN delta_count ELSE 0 END) as Logs,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_metric_points' THEN delta_count ELSE 0 END) as Metrics,\n    sum(CASE WHEN MetricName = 'otelcol_receiver_accepted_spans' THEN delta_count ELSE 0 END) as Traces,\n    sum(delta_count) as Total\nFROM telemetry_data\nGROUP BY ServiceName\nORDER BY Total DESC",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  }
 ]
}