{
 "title": "Clickhouse Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "svc",
    "label": "Cluster",
    "query": {
     "query": "SELECT distinct ServiceName from $table \nwhere $timeFilter\nand ServiceName like '%-clickhouse'\nand MetricName like 'chi_clickhouse_event_SelectedRows'"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "SELECT distinct Attributes['hostname'] from $table where $timeFilter\nAND MetricName = 'chi_clickhouse_event_Query'\nAND ServiceName = $svc"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumns(Attributes['hostname'],  Value) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_Query'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='Clickhouse Health', user='2' */\nSELECT t, groupArray((perSecondColumns, max_0_PerSecond)) AS groupArr FROM ( SELECT t, perSecondColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(perSecondColumns,1,perSecondColumns) OVER () != perSecondColumns, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / (t/1000 - lagInFrame(t/1000,1,0) OVER ())) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['hostname'] AS perSecondColumns, max(Value) AS max_0 from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752252568,3) AND TimeUnix <= toDateTime64(1752256168,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_Query'\nAND Attributes['hostname'] in ('chi-clickhouse-default-0-0.default.svc.cluster.local') GROUP BY t, perSecondColumns ORDER BY perSecondColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(Attributes['hostname'],  Value) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_QueryTimeMicroseconds'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='New dashboard', user='2' */\nSELECT t, groupArray((increaseColumns, max_0_Increase)) AS groupArr FROM ( SELECT t, increaseColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(increaseColumns,1,increaseColumns) OVER () != increaseColumns, 0, max_0 - lagInFrame(max_0,1,0) OVER ()) AS max_0_Increase FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) AS t, Attributes['hostname'] AS increaseColumns, max(Value) AS max_0 from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752232447,3) AND TimeUnix <= toDateTime64(1752254047,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_QueryTimeMicroseconds'\nAND Attributes['hostname'] in ('chi-clickhouse-ch-01-0-0.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-1.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-2.clickhouse.svc.cluster.local') GROUP BY t, increaseColumns ORDER BY increaseColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Merges Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumns(Attributes['hostname'],  Value) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_Merge'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='Clickhouse Health', user='2' */\nSELECT t, groupArray((perSecondColumns, max_0_PerSecond)) AS groupArr FROM ( SELECT t, perSecondColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(perSecondColumns,1,perSecondColumns) OVER () != perSecondColumns, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / (t/1000 - lagInFrame(t/1000,1,0) OVER ())) AS max_0_PerSecond FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (20 * 1000)) * (20 * 1000)) AS t, Attributes['hostname'] AS perSecondColumns, max(Value) AS max_0 from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752232879,3) AND TimeUnix <= toDateTime64(1752254479,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_Merge'\nAND Attributes['hostname'] in ('chi-clickhouse-ch-01-0-0.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-1.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-2.clickhouse.svc.cluster.local') GROUP BY t, perSecondColumns ORDER BY perSecondColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Selected Rows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(Attributes['hostname'],  Value) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_SelectedRows'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='Clickhouse Health', user='2' */\nSELECT t, groupArray((increaseColumns, max_0_Increase)) AS groupArr FROM ( SELECT t, increaseColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(increaseColumns,1,increaseColumns) OVER () != increaseColumns, 0, max_0 - lagInFrame(max_0,1,0) OVER ()) AS max_0_Increase FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (20 * 1000)) * (20 * 1000)) AS t, Attributes['hostname'] AS increaseColumns, max(Value) AS max_0 from base14.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1752252568,3) AND TimeUnix <= toDateTime64(1752256168,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_event_SelectedRows'\nAND Attributes['hostname'] in ('chi-clickhouse-ch-01-0-0.clickhouse.svc.cluster.local') GROUP BY t, increaseColumns ORDER BY increaseColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(Attributes['hostname'] Host,  max(Value) DiskFreeBytes) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_metric_DiskFreeBytes'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='Clickhouse Health', user='2' */\nSELECT t, groupArray((Host, DiskFreeBytes)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['hostname'] Host, max(Value) DiskFreeBytes from base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752252568,3) AND TimeUnix <= toDateTime64(1752256168,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_metric_DiskFreeBytes'\nAND Attributes['hostname'] in ('chi-clickhouse-ch-01-0-0.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-1.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-2.clickhouse.svc.cluster.local') GROUP BY t, Host ORDER BY t, Host) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "OS Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(Attributes['hostname'] Host,  max(Value) DiskFreeBytes) from $table \nwhere ServiceName = $svc\nAND MetricName = 'chi_clickhouse_metric_OSMemoryAvailable'\nAND Attributes['hostname'] in ($host)\n",
     "rawQuery": "/* grafana dashboard='Clickhouse Health', user='2' */\nSELECT t, groupArray((Host, DiskFreeBytes)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t, Attributes['hostname'] Host, max(Value) DiskFreeBytes from base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1752252568,3) AND TimeUnix <= toDateTime64(1752256168,3) AND ServiceName = $svc\nAND MetricName = 'chi_clickhouse_metric_OSMemoryAvailable'\nAND Attributes['hostname'] in ('chi-clickhouse-ch-01-0-0.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-1.clickhouse.svc.cluster.local','chi-clickhouse-ch-01-0-2.clickhouse.svc.cluster.local') GROUP BY t, Host ORDER BY t, Host) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}