{
 "title": "Traces Collected",
 "tags": [ "health" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "SELECT DISTINCT ServiceName\nFROM $table\nWHERE Timestamp > now() - INTERVAL 1 day"
    }
   },
   { "name": "searchText", "label": "Span Name" }
  ]
 },
 "panels": [
  {
   "title": "Unique Spans by Service",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    DISTINCT(ServiceName) as Service,\n    COUNT(DISTINCT(SpanName)) as NumberOfSpans \nFROM $table\nWHERE $timeFilter\nGROUP BY Service\nORDER BY NumberOfSpans DESC",
     "rawQuery": "/* grafana dashboard='Traces Collected', user='6' */\nSELECT\n    DISTINCT(ServiceName) as Service,\n    COUNT(DISTINCT(SpanName)) as NumberOfSpans \nFROM base14.otel_traces\nWHERE Timestamp >= toDateTime64(1753351014,3) AND Timestamp <= toDateTime64(1753351314,3)\nGROUP BY Service\nORDER BY NumberOfSpans DESC",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Total Spans by Service",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    DISTINCT(ServiceName) AS Service,\n    COUNT(SpanName) AS NumberOfSpans \nFROM $table\nWHERE $timeFilter\nGROUP BY Service\nORDER BY NumberOfSpans DESC",
     "rawQuery": "/* grafana dashboard='Traces Collected', user='6' */\nSELECT\n    DISTINCT(ServiceName) AS Service,\n    COUNT(SpanName) AS NumberOfSpans \nFROM base14.otel_traces\nWHERE Timestamp >= toDateTime64(1753351014,3) AND Timestamp <= toDateTime64(1753351314,3)\nGROUP BY Service\nORDER BY NumberOfSpans DESC",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "All Metrics by Type",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "base14",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT DISTINCT SpanName, ServiceName \nFROM $table\nWHERE $timeFilter\nAND (ServiceName IS NOT NULL AND ServiceName in (${service:singlequote}))\nAND SpanName ilike '%${searchText:raw}%'\nORDER BY ServiceName, SpanName\nLIMIT 100",
     "rawQuery": "/* grafana dashboard='Traces Collected', user='6' */\nSELECT DISTINCT SpanName, ServiceName \nFROM base14.otel_traces\nWHERE Timestamp >= toDateTime64(1753351014,3) AND Timestamp <= toDateTime64(1753351314,3)\nAND (ServiceName IS NOT NULL AND ServiceName in ())\nAND SpanName ilike '%%'\nORDER BY ServiceName, SpanName\nLIMIT 100",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  }
 ]
}