{
 "title": "k8s Node stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Node Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.available'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=k8s pods, user=1 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (60 * 1000)) * (60 * 1000)) as t, count() FROM base14.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1735381163, 3) AND TimeUnix <= toDateTime64(1735402763, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Memory RSS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.rss'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.memory.rs' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Memory Page Faults",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.page_faults'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, ma(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.memory.page_faults' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Memory Major Page Faults",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.major_page_faults'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.memory.major_page_faults\n' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.usage'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.memory.usage\n' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Memory WorkingSet",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.memory.working_set'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.memory.working_set\n' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  { "title": "Node Filesystem Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Filesystem usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.filesystem.usage'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735399567, 3) AND TimeUnix <= toDateTime64(1735403167, 3) AND TimeUnix >= toDateTime64(1735399567, 3) AND TimeUnix <= toDateTime64(1735403167, 3) \nAND MetricName = 'k8s.node.cpu.utilization' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Filesystem capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.filesystem.capacity'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.filesystem.capacity\n' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Node Filesystem available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.filesystem.available'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.filesystem.available\n' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  { "title": "Node CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node CPU Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.cpu.time'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) AND TimeUnix >= toDateTime64(1735400349, 3) AND TimeUnix <= toDateTime64(1735403949, 3) \nAND MetricName = 'k8s.node.cpu.time' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Node CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.node.name'] name, max(Value) v) \nFROM $table \nWHERE $timeFilter \nAND MetricName = 'k8s.node.cpu.utilization'\nGROUP BY t, ResourceAttributes['k8s.node.name'] \nORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((name, v)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (5 * 1000)) * (5 * 1000)) AS t, ResourceAttributes['k8s.node.name'] name, max(Value) v FROM base14.otel_metrics_gauge \nWHERE TimeUnix >= toDateTime64(1735399567, 3) AND TimeUnix <= toDateTime64(1735403167, 3) AND TimeUnix >= toDateTime64(1735399567, 3) AND TimeUnix <= toDateTime64(1735403167, 3) \nAND MetricName = 'k8s.node.memory.available' GROUP BY t, ResourceAttributes['k8s.node.name']  ORDER BY t) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}