{
 "title": "Clickhouse Basic Table Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Table sizes (combined for Cluster)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select parts.table,\n       parts.rows,\n       columns.compressed_size,\n       columns.uncompressed_size,\n       columns.ratio\nfrom (\n         select table,\n                formatReadableSize(sum(data_uncompressed_bytes))          AS uncompressed_size,\n                formatReadableSize(sum(data_compressed_bytes))            AS compressed_size,\n                sum(data_compressed_bytes) / sum(data_uncompressed_bytes) AS ratio\n         from clusterAllReplicas(default, system.columns)\n         where database = currentDatabase()\n         group by table\n         ) columns\n         right join (\n    select table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from clusterAllReplicas(default, system.parts)\n    where active and database = currentDatabase()\n    group by database, table\n    ) parts on columns.table = parts.table\norder by parts.bytes_size desc",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nselect parts.table,\n       parts.rows,\n       columns.compressed_size,\n       columns.uncompressed_size,\n       columns.ratio\nfrom (\n         select table,\n                formatReadableSize(sum(data_uncompressed_bytes))          AS uncompressed_size,\n                formatReadableSize(sum(data_compressed_bytes))            AS compressed_size,\n                sum(data_compressed_bytes) / sum(data_uncompressed_bytes) AS ratio\n         from clusterAllReplicas(default,system.columns)\n         where database = currentDatabase()\n         group by table\n         ) columns\n         right join (\n    select table,\n           sum(rows)                                            as rows,\n           max(modification_time)                               as latest_modification,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from clusterAllReplicas(default, system.parts)\n    where active and database = currentDatabase()\n    group by database, table\n    ) parts on columns.table = parts.table\norder by parts.bytes_size desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Inserts in timeperiod",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() as Logs FROM $table WHERE $timeFilter",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT count() as Log FROM default.otel_logs WHERE Timestamp >= toDateTime64(1734615033, 3) AND Timestamp <= toDateTime64(1734615333, 3)",
     "round": "0s",
     "table": "otel_logs"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() as Metrics  FROM $table WHERE $timeFilter ",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT count() as Metric  FROM default.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1734615033, 3) AND TimeUnix <= toDateTime64(1734615333, 3)",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() as Traces FROM $table WHERE $timeFilter",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT count() as Trace FROM default.otel_traces WHERE Timestamp >= toDateTime64(1734615033, 3) AND Timestamp <= toDateTime64(1734615333, 3)",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Rate of inserts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    count() AS \"c_$table\"\nFROM $table\nGROUP BY t\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT\n    (intDiv(toFloat64(Timestamp) * 1000, (0 * 1000)) * (0 * 1000)) AS t,\n    count() AS \"c_default.otel_logs\"\nFROM default.otel_logs\nGROUP BY t\nORDER BY t ASC",
     "round": "0s",
     "table": "otel_logs"
    },
    {
     "database": "default",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    count() AS \"c_$table\"\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT\n    (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) AS t,\n    count() AS \"c_default.otel_metrics_gauge\"\nFROM default.otel_metrics_gauge\nWHERE $tim\nGROUP BY t\nORDER BY t ASC",
     "round": "0s",
     "table": "otel_metrics_gauge"
    },
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    count() AS \"c_$table\"\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t ASC\n",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nSELECT\n    (intDiv(toFloat64(undefined) * 1000, (2 * 1000)) * (2 * 1000)) AS t,\n    count() AS \"c_default.otel_traces\"\nFROM default.otel_traces\nWHERE undefined >= toDateTime64(1734602222, 3) AND undefined <= toDateTime64(1734604022, 3)\nGROUP BY t\nORDER BY t ASC",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select Timestamp, Body, ResourceAttributes, TraceId from otel_logs where $timeFilter order by Timestamp DESC limit 1000",
     "rawQuery": "/* grafana dashboard=Basics, user=1 */\nselect Timestamp, Body, ResourceAttributes, TraceId from otel_logs where Timestamp >= toDateTime64(1734591476, 3) AND Timestamp <= toDateTime64(1734613076, 3) order by Timestamp desc limit 1000",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  }
 ]
}