{
 "title": "k8s pods",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Deployments by Phase",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $timeSeries t, Value, count(distinct(ResourceAttributes['k8s.deployment.name'])) Deployments from $table where $timeFilter \nAND MetricName = 'k8s.pod.phase' \nAND ResourceAttributes['k8s.deployment.name'] != ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by t, Value  order by t \n  ",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nselect (intDiv(toFloat64(TimeUnix) * 1000, (30 * 1000)) * (30 * 1000)) t, Value, count(distinct(ResourceAttributes['k8s.deployment.name'])) Deployments from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1735338906, 3) AND TimeUnix <= toDateTime64(1735382106, 3) \nAND MetricName = 'k8s.pod.phase' \nAND ResourceAttributes['k8s.deployment.name'] != ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by t, Value  order by t desc",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Statefulsets by Phase",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $timeSeries t, Value, count(distinct(ResourceAttributes['k8s.statefulset.name'])) Deployments from $table where $timeFilter \nAND MetricName = 'k8s.pod.phase' \nAND ResourceAttributes['k8s.statefulset.name'] != ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by t, Value  order by t \n  ",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nselect (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, Value, count(distinct(ResourceAttributes['k8s.statefulset.name'])) Deployments from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1735380330, 3) AND TimeUnix <= toDateTime64(1735382130, 3) \nAND MetricName = 'k8s.pod.phase' \nAND ResourceAttributes['k8s.deployment.name'] != ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by t, Value  order by t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Other pods by Phase",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $timeSeries t, Value, count(distinct(ResourceAttributes['k8s.pod.name']))  from $table where $timeFilter \nAND MetricName = 'k8s.pod.phase' \n  and ResourceAttributes['k8s.deployment.name'] == ''\n  and ResourceAttributes['k8s.statefulset.name'] == ''\n  and ResourceAttributes['k8s.daemonset.name'] == ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by t, Value  order by t ",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nselect (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, Value, count(distinct(ResourceAttributes['k8s.pod.name']))  from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1735379543, 3) AND TimeUnix <= toDateTime64(1735383143, 3) \nAND MetricName = 'k8s.pod.phase' \n  and ResourceAttributes['k8s.deployment.name'] == ''\n  and ResourceAttributes['k8s.statefulset.name'] == ''\n  and ResourceAttributes['k8s.daemonset.name'] == ''\n  and ResourceAttributes['k8s.namespace.name'] != 'kube-system'\ngroup by Value  order by t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Kube System Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $timeSeries t, Value, count(distinct(ResourceAttributes['k8s.pod.name'])) Deployments from $table where $timeFilter \nAND MetricName = 'k8s.pod.phase' \n  and ResourceAttributes['k8s.namespace.name'] == 'kube-system'\ngroup by t, Value  order by t \n  ",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nselect (intDiv(toFloat64(TimeUnix) * 1000, (2 * 1000)) * (2 * 1000)) t, Value, count(distinct(ResourceAttributes['k8s.po.name'])) Deployments from base14.otel_metrics_gauge where TimeUnix >= toDateTime64(1735380392, 3) AND TimeUnix <= toDateTime64(1735382192, 3) \nAND MetricName = 'k8s.pod.phase' \n  and ResourceAttributes['k8s.namespace.name'] == 'kube-system'\ngroup by t, Value  order by t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Total Restarts",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.container.name'] container, anyLast(Value) c) from $table where $timeFilter \nAND MetricName = 'k8s.container.restarts' ",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((container, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (300 * 1000)) * (300 * 1000)) AS t, ResourceAttributes['k8s.container.name'] container, anyLast(Value) c from base14.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1735205207, 3) AND TimeUnix <= toDateTime64(1735378007, 3) AND TimeUnix >= toDateTime64(1735205207, 3) AND TimeUnix <= toDateTime64(1735378007, 3) \nAND MetricName = 'k8s.container.restart' GROUP BY t, container ORDER BY t, container) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Restarts In period",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(ResourceAttributes['k8s.container.name'], Value) from $table where MetricName = 'k8s.container.restarts'",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT t, groupArray((increaseColumns, max_0_Increase)) AS groupArr FROM ( SELECT t, increaseColumns, if(runningDifference(max_0) < 0 OR neighbor(increaseColumns,-1,increaseColumns) != increaseColumns, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (20 * 1000)) * (20 * 1000)) AS t, ResourceAttributes['k8s.container.name'] AS increaseColumns, max(Value) AS max_0 from base14.otel_metrics_gauge WHERE TimeUnix >= toDateTime64(1735368315, 3) AND TimeUnix <= toDateTime64(1735379115, 3) AND MetricName = 'k8s.container.restarts' GROUP BY t, increaseColumns ORDER BY increaseColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Successful Pods in Period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c) from $table\nWHERE MetricName = 'k8s.pod.phase' and Value = 3",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nSELECT t, groupArray((container, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c from base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1735373828, 3) AND TimeUnix <= toDateTime64(1735384628, 3) AND MetricName = 'k8s.pod.phase' and Value = GROUP BY t, container ORDER BY t, container) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Failed Pods in Period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c) from $table\nwhere MetricName = 'k8s.pod.phase' and Value = 4",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nSELECT t, groupArray((container, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c from base14.otel_metrics_gauge\nwher MetricName = 'k8s.pod.phase' and Value = 4 WHERE TimeUnix >= toDateTime64(1735372831, 3) AND TimeUnix <= toDateTime64(1735383631, 3) GROUP BY t, container ORDER BY t, container) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Pending Pods in Period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c) from $table\nWHERE MetricName = 'k8s.pod.phase' and Value = 1",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nSELECT t, groupArray((container, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c from base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1735372831, 3) AND TimeUnix <= toDateTime64(1735383631, 3) ANDMetricName = 'k8s.pod.phase' and Value = 1 GROUP BY t, container ORDER BY t, container) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  },
  {
   "title": "Phase-unknown Pods in Period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "base14",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c) from $table\nWHERE MetricName = 'k8s.pod.phase' and Value = 5",
     "rawQuery": "/* grafana dashboard=k8s stats, user=1 */\nSELECT t, groupArray((container, c)) AS groupArr FROM ( SELECT (intDiv(toFloat64(TimeUnix) * 1000, (10 * 1000)) * (10 * 1000)) AS t, ResourceAttributes['k8s.pod.name'] container, anyLast(Value) c from base14.otel_metrics_gauge\nWHERE TimeUnix >= toDateTime64(1735372831, 3) AND TimeUnix <= toDateTime64(1735383631, 3) AND MetricName = 'k8s.pod.phase' and Value = GROUP BY t, container ORDER BY t, container) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_gauge"
    }
   ]
  }
 ]
}